# Generated by Django 5.1.6 on 2025-07-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_courseassignment_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
