# Generated by Django 5.1.6 on 2025-07-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timetableentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='timetable_id',
        ),
    ]
