# Generated by Django 5.2.3 on 2025-07-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timetable_timetableentry_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='short_name',
            field=models.CharField(max_length=20),
        ),
    ]
