# Generated by Django 5.0.6 on 2025-08-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_labblock_roomblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('1_hour', '1 Hour Slot'), ('2_hour', '2 Hour Pair Slot')], default='1_hour', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'verbose_name': 'Timetable Type',
                'verbose_name_plural': 'Timetable Types',
            },
        ),
    ]
