# Generated by Django 5.0.6 on 2025-09-10 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_facultypreferredslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabletype',
            name='lab_hours',
            field=models.IntegerField(choices=[(1, '1 Hour Lab'), (2, '2 Hour Lab')], default=1, help_text='Lab duration for TYPE-0 timetable (only applicable when slot_type is type_0)'),
        ),
        migrations.AlterField(
            model_name='timetabletype',
            name='slot_type',
            field=models.CharField(choices=[('1_hour', '1 Hour Slot'), ('2_hour', '2 Hour Pair Slot'), ('type_0', 'TYPE-0 (Unique Subject Assignment)')], default='1_hour', max_length=10),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('day_name', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('faculty', 'day_name')},
            },
        ),
        migrations.CreateModel(
            name='LeaveReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=20)),
                ('room_or_lab', models.CharField(max_length=100)),
                ('is_temporary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
                ('original_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_lectures', to='core.faculty')),
                ('replacement_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_lectures', to='core.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursespec')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='core.leaverequest')),
            ],
            options={
                'unique_together': {('leave_request', 'batch', 'subject', 'time_slot')},
            },
        ),
    ]
