# Generated by Django 5.1.13 on 2026-03-03 14:28

from django.db import migrations, models


def migrate_slot_type_to_2hour(apps, schema_editor):
    """Migrate existing 1_hour and type_0 to 2_hour before altering choices."""
    TimetableType = apps.get_model('core', 'TimetableType')
    TimetableType.objects.filter(slot_type__in=['1_hour', 'type_0']).update(slot_type='2_hour')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_timetabletype_lab_hours_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_slot_type_to_2hour, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='timetabletype',
            name='lab_hours',
        ),
        migrations.AlterField(
            model_name='timetabletype',
            name='slot_type',
            field=models.CharField(choices=[('2_hour', '2 Hour Pair Slot')], default='2_hour', max_length=10),
        ),
    ]
