# Generated by Django 5.1.6 on 2025-07-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_facultyblock_delete_facultyslotblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_start', models.DateField()),
                ('t1_end', models.DateField()),
                ('t2_start', models.DateField()),
                ('t2_end', models.DateField()),
                ('t3_start', models.DateField()),
                ('t3_end', models.DateField()),
                ('t4_start', models.DateField()),
                ('t4_end', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
    ]
