# Generated by Django 5.1.6 on 2025-07-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0011_facultyblock_delete_facultyslotblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancephase',
            name='t1_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancephase',
            name='t1_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancephase',
            name='t2_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancephase',
            name='t2_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancephase',
            name='t3_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancephase',
            name='t3_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancephase',
            name='t4_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancephase',
            name='t4_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('student_roll', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('lecture', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timetable')),
            ],
        ),
    ]
