# Generated by Django 5.1.6 on 2025-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancephase_t1_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancephase',
            name='t1_end',
        ),
        migrations.RemoveField(
            model_name='attendancephase',
            name='t1_start',
        ),
        migrations.RemoveField(
            model_name='attendancephase',
            name='t2_end',
        ),
        migrations.RemoveField(
            model_name='attendancephase',
            name='t2_start',
        ),
        migrations.RemoveField(
            model_name='attendancephase',
            name='t3_end',
        ),
        migrations.RemoveField(
            model_name='attendancephase',
            name='t3_start',
        ),
        migrations.RemoveField(
            model_name='attendancephase',
            name='t4_end',
        ),
        migrations.RemoveField(
            model_name='attendancephase',
            name='t4_start',
        ),
        migrations.AddField(
            model_name='attendancephase',
            name='end_date',
            field=models.DateField(default='2025-07-01'),
        ),
        migrations.AddField(
            model_name='attendancephase',
            name='phase',
            field=models.CharField(default='2025-07-01', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancephase',
            name='start_date',
            field=models.DateField(default='2025-07-01'),
            preserve_default=False,
        ),
    ]
