# Generated by Django 5.2.3 on 2025-07-31 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancephase_t1_end_and_more'),
        ('core', '0012_batchroomlabmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='department',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='timetable',
        ),
        migrations.CreateModel(
            name='AttendanceSessionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_start', models.DateField(blank=True, null=True)),
                ('t1_end', models.DateField(blank=True, null=True)),
                ('t2_start', models.DateField(blank=True, null=True)),
                ('t2_end', models.DateField(blank=True, null=True)),
                ('t3_start', models.DateField(blank=True, null=True)),
                ('t3_end', models.DateField(blank=True, null=True)),
                ('t4_start', models.DateField(blank=True, null=True)),
                ('t4_end', models.DateField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendancePhase',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
